version: '3.0'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_DB: marsel_db
      POSTGRES_USER: marsel
      POSTGRES_PASSWORD: 123456
    ports:
      - "5431:5432"
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
  
  django:
    build: .
    ports:
      - "8000:8000"
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_DB: marsel_db
      POSTGRES_USER: marsel
      POSTGRES_PASSWORD: 123456
      
      # Redis
      REDIS_HOST: redis
      REDIS_PORT: 6479 

    depends_on:
      - postgres
      - redis

  celery:
    build: .
    command: celery -A core worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis

  flower:
    build: .
    command: celery flower --broker=redis://redis:6379
    ports:
      - "5555:5555"
    volumes:
      - .:/app
    depends_on:
      - redis
      - celery

  redis:
    image: redis:latest
    ports:
      - "6479:6479"

  bot:
    build: .
    command: python3 bot.py
    volumes:
      - .:/app
    depends_on:
      - django


volumes:
  postgres_data:
  